Repository kubernetes/contrib, pull requests merged in 2018-02, with the labels that each got.

#2855 Load benchmark metrics.
  perfdash/config.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2856 Bump version.
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2857 add option to show actual output to exechealthz
  exec-healthz/cmd/exechealthz/exechealthz.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2847 Fix typo
  node-perf-dash/node-perf-dash.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2846 Add link to redirect
  metadata-proxy/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2862 The github.com/GoogleCloudPlatform/kubernetes is no more.
  init/systemd/kube-apiserver.service
  init/systemd/kube-controller-manager.service
  init/systemd/kube-proxy.service
  init/systemd/kube-scheduler.service
  init/systemd/kubelet.service
Labels: approved, cncf-cla: yes, lgtm, size/S
