Repository kubernetes/contrib, pull requests merged in 2018-04, with the labels that each got.

#2881 Fix grammar mistake
  statefulsets/kafka/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2878 Adding metrics for apiserver request count.
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2877 Bump to golang-1.10 and update docker base image
  exec-healthz/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2884 Update doc + owners
  perfdash/OWNERS
  perfdash/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2890 Typo fix comand->command
  continuousdelivery/deploy/deploy-service.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
