Repository kubernetes/contrib, pull requests merged in 2018-06, with the labels that each got.

#2845 [keepalived-vip] typo in IP address and virtual_ipaddress should same as virtual_server
  keepalived-vip/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2911 Typo fix: kubeclt->kubectl
  service-loadbalancer/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2920 Typo fix in path: kubernets->kubernetes
  ansible/roles/kubernetes/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2922 Rescheduler considers pods critical only when they are in kube-system namespace
  rescheduler/rescheduler.go
  rescheduler/rescheduler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2924 Update Rescheduler's version tag
  rescheduler/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2926 Fix Rescheduler Makefile
  rescheduler/Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
